[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/925kxcs2gipqs3qznf0nspvwx33nlxdh-noctalia-shell-4.5.0/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/zm/.cache/noctalia/placeholder.json"

[templates.nvim-base16]
input_path = "~/.config/noctalia/templates/neovim.lua"
output_path = "~/.config/nvim/lua/colors/noctalia.lua"
post_hook = 'pkill -SIGUSR1 nvim'

[templates.fcitx5]
input_path = "~/.config/noctalia/templates/fcitx5.conf"
output_path = "~/.local/share/fcitx5/themes/noctalia/theme.conf"
post_hook = 'fcitx5 -r'
